### ISSUE TITLE
Analyze the overlap between OpenTelemetry tracing attributes and ECS attributes

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#1012]
## [HTTP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md)
- [x] open-telemetry/opentelemetry-specification#3181
- [x] open-telemetry/opentelemetry-specification#3182
- [x] open-telemetry/opentelemetry-specification#3199 
- [x] open-telemetry/opentelemetry-specification#3371 

## [Exceptions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md)
- [x] open-telemetry/opentelemetry-specification#3198 

## [General remote service attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#general-remote-service-attributes)

@AlexanderWert to confirm that ECS doesn't have an equivalent to `peer.service`.

## [General identity attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#general-identity-attributes)

| OpenTelemetry | ECS |
| --- | --- |
| `enduser.id` | `user.id` |
| `enduser.role`, `enduser.scope` | `user.roles` (?) |

## [General thread attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#general-thread-attributes)

| OpenTelemetry | ECS |
| --- | --- |
| `thread.id` | `process.thread.id` |
| `thread.name` | `process.thread.name` |

## [Source code attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#source-code-attributes)

| OpenTelemetry | ECS |
| --- | --- |
| `code.function` | `log.origin.function` |
| `code.namespace` |  |
| `code.filepath` | `log.origin.file.name` |
| `code.lineno` | `log.origin.file.line` |
| `code.column` |   |

## [Messaging](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md)

This is also discussed/tracked at open-telemetry/opentelemetry-specification#3196.

Only impacted by network attribute changes above (#3199 and open-telemetry/opentelemetry-specification#3371).

(ECS doesn't have any messaging-specific attributes, @AlexanderWert to confirm)

Could also be impacted by conflict with `source.*` and `destination.*` namespace, see https://github.com/open-telemetry/opentelemetry-specification/issues/3407

## [Database](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md)

Only impacted by network attribute changes above (#3199 and open-telemetry/opentelemetry-specification#3371).

(ECS doesn't have any database-specific attributes, @AlexanderWert to confirm).

## [RPC](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/rpc.md)

Only impacted by network attribute changes above (#3199 and open-telemetry/opentelemetry-specification#3371).

(ECS doesn't have any RPC-specific attributes, @AlexanderWert to confirm).

## FaaS [tracing](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/faas.md) and [resources](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/faas.md)

| OpenTelemetry | ECS |
| --- | --- |
| `faas.coldstart` | `faas.coldstart` |
| `faas.invocation_id` | `faas.execution` |
| `cloud.resource_id` | `faas.id` |
| `faas.name` | `faas.name` |
|  | `faas.trigger.request_id` |
| `faas.trigger` | `faas.trigger.type` |
| `faas.version` | `faas.version` |

## [CloudEvents](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/cloudevents.md)

ECS doesn't have any cloud event specific attributes (@AlexanderWert to confirm)

## [Feature Flags](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/feature-flags.md)

ECS doesn't have any feature flag specific attributes (@AlexanderWert to confirm)

**Comment by AlexanderWert** [comment]
Closing as we'll track the individual areas while working on SemConv / continuously contributing ECS fields to SemConv
