### ISSUE TITLE
[editorial] Rename pages under /docs/general/ to avoid `general` in the page name, etc

### ISSUE THREAD

**Issue by chalin** [open-telemetry/semantic-conventions#194]
For sake of uniformity and brievity in page naming (which appear as URLs on the website), we might want to consider renaming some page files to drop the filename part that repeats the section name.

For example, here are the pages names under the [general](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/general) section:

```console
$ (cd docs/general/ && find . -type f) | sort                     
./README.md
./events-general.md
./general-attributes.md
./logs-general.md
./metrics-general.md
./trace-compatibility.md
./trace-general.md
```

I'd suggest dropping `general` from the page names, to give:

```console
$ (cd docs/general/ && find . -type f) | sort | perl -pe 's/-?general-?//g'
./README.md
./events.md
./attributes.md
./logs.md
./metrics.md
./trace-compatibility.md
./trace.md
```

WDYT? If you agree, we'll need to add `aliases` to the front matter.

If you agree, we might also want to do a similar simplification of names of all the sections listed below.

### Tasks

- [x] [general](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/general) - #195
- [ ] [exceptions](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/exceptions)
- [ ] [faas](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/faas)
- [ ] [feature-flags](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/feature-flags)
- [ ] [http](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/http)
- [ ] [messaging](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/messaging) - only one page to rename
- [ ] [http](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/http)
- [ ] [rpc](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/rcp)
- [ ] [http](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/http)

/cc @svrnm @cartermp

**Comment by joaopgrassi** [comment]
@chalin is this still needed? The bot closed it by mistake, but I'm not sure if we still need this. Please let me know so I can either keep it closed or re-open it.

**Comment by chalin** [comment]
@joaopgrassi - yes, this is still relevant. Thanks for reopening it.

**Comment by lmolkova** [comment]
I'd be in favor of even moving common docs one level up to /docs folder.  
 I always expect them to be there since they are not domain-specific.
