### ISSUE TITLE
Tracking semconv build-tools 0.24.0 release readiness and roll out plan

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#807]
The next version of build-tools will contain the following new features:
- [BREAKING] Requires explicit stability on each metric, attribute, and enum member and renders it on everything
  - [x] https://github.com/open-telemetry/build-tools/pull/267
  - [x] https://github.com/open-telemetry/build-tools/pull/272
  - [x] https://github.com/open-telemetry/build-tools/pull/244
  - [x] https://github.com/open-telemetry/build-tools/pull/278
- [x] Add backward compatibility check - https://github.com/open-telemetry/build-tools/pull/271
- [x] Code generation improvements - https://github.com/open-telemetry/build-tools/pull/295
- [x] Support lenient yaml validation for code generation and back-compat checks  - https://github.com/open-telemetry/build-tools/pull/300
- various cosmetic improvements

Here're the work items we need to complete inside semconv repo prior to updating build-tools version:
- [x] https://github.com/open-telemetry/semantic-conventions/pull/801
- [x] https://github.com/open-telemetry/semantic-conventions/pull/819

Update to 0.24.0 PR and fix new violations
- [ ] https://github.com/open-telemetry/semantic-conventions/pull/820

After update:
- [ ] https://github.com/open-telemetry/semantic-conventions/pull/764
- Unblock PRs blocked on resource/span attributes:
   - [ ]  https://github.com/open-telemetry/semantic-conventions/pull/681
   - [ ]  https://github.com/open-telemetry/semantic-conventions/pull/758
- Language SIGs can start using new code-generation

**Comment by gregkalapos** [comment]
I rebased https://github.com/open-telemetry/semantic-conventions/pull/758 and generated the new md files.
